// <auto-generated />
using System;
using Dominica.Learn.Infrastructure.Indice;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dominica.Learn.Infrastructure.Indice.Migracoes
{
    [DbContext(typeof(ContextoDoIndice))]
    [Migration("20260806154838_IsolamentoPorUsuario")]
    partial class IsolamentoPorUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dominica.Learn.Infrastructure.Indice.EtiquetaNoIndice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NotaId")
                        .HasColumnType("integer");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("NotaId");

                    b.HasIndex("Usuario", "Valor");

                    b.ToTable("etiquetas", (string)null);
                });

            modelBuilder.Entity("Dominica.Learn.Infrastructure.Indice.LigacaoNoIndice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alvo")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Destino")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Forma")
                        .HasColumnType("integer");

                    b.Property<int>("NotaId")
                        .HasColumnType("integer");

                    b.Property<int>("Posicao")
                        .HasColumnType("integer");

                    b.Property<string>("Rotulo")
                        .HasColumnType("text");

                    b.Property<string>("Secao")
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("NotaId");

                    b.HasIndex("Usuario", "Destino");

                    b.ToTable("ligacoes", (string)null);
                });

            modelBuilder.Entity("Dominica.Learn.Infrastructure.Indice.NotaNoIndice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apelidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Impressao")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ModificadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Palavras")
                        .HasColumnType("integer");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ModificadoEm");

                    b.HasIndex("Usuario", "Caminho")
                        .IsUnique();

                    b.ToTable("notas", (string)null);
                });

            modelBuilder.Entity("Dominica.Learn.Infrastructure.Indice.RevisaoNoIndice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Autor")
                        .HasColumnType("text");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Em")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Usuario", "Caminho", "Em");

                    b.ToTable("revisoes", (string)null);
                });

            modelBuilder.Entity("Dominica.Learn.Infrastructure.Indice.EtiquetaNoIndice", b =>
                {
                    b.HasOne("Dominica.Learn.Infrastructure.Indice.NotaNoIndice", "Nota")
                        .WithMany("Etiquetas")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("Dominica.Learn.Infrastructure.Indice.LigacaoNoIndice", b =>
                {
                    b.HasOne("Dominica.Learn.Infrastructure.Indice.NotaNoIndice", "Nota")
                        .WithMany("Ligacoes")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("Dominica.Learn.Infrastructure.Indice.NotaNoIndice", b =>
                {
                    b.Navigation("Etiquetas");

                    b.Navigation("Ligacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
